

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile        # prod image by default
    container_name: mportal_app
    ports:
      - "8787:8787"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
    networks: [app-network]

  frontend:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile        # prod (nginx/static) by default
    container_name: mportal_frontend
    ports:
      - "3001:80"
    networks: [app-network]

networks:
  app-network:
    driver: bridge
