

services:
  postgres:
    image: postgres:15
    container_name: mportal_postgres
    restart: always
    ports:
      - "5434:5432"  # Avoids port conflict with other projects
    volumes:
      - mportal_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mportal
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mportal_db
    networks:
      - app-network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mportal_app
    restart: unless-stopped
    working_dir: /var/www/html/mportal
    volumes:
      - ./backend:/var/www/html/mportal
    ports:
      - "8787:8787"
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: mportal_db
      DB_USERNAME: mportal
      DB_PASSWORD: secret
    command: >
      sh -c "
      mkdir -p storage/logs storage/framework/{cache,sessions,views} bootstrap/cache &&
      chown -R www-data:www-data storage bootstrap/cache || true &&
      chmod -R 775 storage bootstrap/cache || true &&
      composer install &&
      php artisan config:cache &&
      php artisan migrate --force &&
      php artisan octane:stop || true &&
      fuser -k 8787/tcp || true &&
      php artisan octane:start --server=swoole --host=0.0.0.0 --port=8787
      "
    networks:
      - app-network



  frontend:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
    container_name: mportal_frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - app-network


volumes:
  mportal_pgdata:

networks:
  app-network:
    driver: bridge
