

services:
  postgres:
    image: postgres:15
    container_name: sucden_postgres
    restart: always
    ports:
      - "5434:5432"  # Avoids port conflict with other projects
    volumes:
      - sucden_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sucden
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sucden_db
    networks:
      - app-network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sucden_app
    restart: unless-stopped
    working_dir: /var/www/html/sucden
    volumes:
      - ./backend:/var/www/html/sucden
    ports:
      - "8686:8686"
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: sucden_db
      DB_USERNAME: sucden
      DB_PASSWORD: secret
    command: >
      sh -c "
      composer install &&
      php artisan config:cache &&
      php artisan migrate --force &&
      php artisan octane:start --server=swoole --host=0.0.0.0 --port=8686
      "
    networks:
      - app-network


  frontend:
    build:
      context: ./frontend-web
      dockerfile: Dockerfile
    container_name: sucden_frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    networks:
      - app-network


volumes:
  sucden_pgdata:

networks:
  app-network:
    driver: bridge
